name: perfect_board_example
description: Esempio minimo di perfect_board sugli emulatori Firebase.
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  firebase_storage: ^13.0.5
  go_router: '>=17.0.1 <19.0.0'
  perfect_board:
    path: ..

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
